import OpenAI from "openai";

import type { AgentMessage } from "@lotclaw/shared-types";

export interface ModelGenerateParams {
  systemPrompt?: string;
  messages: AgentMessage[];
}

export interface ModelGenerateResult {
  outputText: string;
  finishReason: "stop" | "length" | "tool_call";
}

export type TaskIntentType = "inspect" | "read" | "write" | "patch" | "analyze";

export interface TaskEntityRef {
  kind: "file" | "directory" | "workspace" | "text";
  path?: string;
  value?: string;
}

export interface TaskConstraint {
  kind: "workspace_only" | "must_create_dirs" | "must_exist" | "single_replace";
  value: boolean | string;
}

export interface TaskIntentStep {
  type: "inspect" | "read" | "write" | "patch" | "analyze" | "finish";
  description: string;
  target?: TaskEntityRef;
  params?: Record<string, string | boolean | number>;
}

export interface TaskIntentSchema {
  type: TaskIntentType;
  summary: string;
  target?: TaskEntityRef;
  inputs: Record<string, string | boolean | number>;
  constraints: TaskConstraint[];
  expectedOutcome: string;
  proposedSteps: TaskIntentStep[];
}

export interface PlanningDecision {
  intent: TaskIntentSchema;
  confidence: number;
  reasoning: string;
}

export interface ToolDescriptor {
  name: string;
  description: string;
  permission: string;
}

export interface ActionObservation {
  toolName: string;
  ok: boolean;
  summary: string;
  data?: unknown;
  errorCode?: string;
}

export type NextAction =
  | {
      type: "tool_call";
      toolName: string;
      input: Record<string, unknown>;
      thought: string;
    }
  | {
      type: "finish";
      finalOutput: string;
      thought: string;
    };

export interface ActionDecisionInput {
  goal: string;
  intent: TaskIntentSchema;
  availableTools: ToolDescriptor[];
  observations: ActionObservation[];
}

export interface ModelAdapter {
  name: string;
  generateText(params: ModelGenerateParams): Promise<ModelGenerateResult>;
  decideTaskIntent(goal: string): Promise<PlanningDecision>;
  decideNextAction(input: ActionDecisionInput): Promise<NextAction>;
}

export interface ModelAdapterOptions {
  provider?: string;
  model?: string;
  apiKey?: string;
  baseURL?: string;
}

export class StubModelAdapter implements ModelAdapter {
  name = "stub";

  async generateText(params: ModelGenerateParams): Promise<ModelGenerateResult> {
    const latest = params.messages[params.messages.length - 1];

    return {
      outputText: latest ? `stub:${latest.content}` : "stub:empty",
      finishReason: "stop"
    };
  }

  async decideTaskIntent(goal: string): Promise<PlanningDecision> {
    const normalized = goal.trim().toLowerCase();

    if (matchesAny(normalized, ["validate loop", "analyze readme", "inspect then read", "agent loop"])) {
      return {
        intent: {
          type: "analyze",
          summary: "Inspect the workspace and then read README.md if it exists.",
          target: {
            kind: "workspace",
            path: "."
          },
          inputs: {
            followUpPath: "README.md"
          },
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_exist", value: true }
          ],
          expectedOutcome: 'The agent should first inspect the workspace, then read "README.md", then finish.',
          proposedSteps: [
            {
              type: "inspect",
              description: "List the workspace root to confirm the README is present.",
              target: {
                kind: "workspace",
                path: "."
              }
            },
            {
              type: "read",
              description: "Read README.md after confirming it exists.",
              target: {
                kind: "file",
                path: "README.md"
              }
            },
            {
              type: "finish",
              description: "Report that the workspace was inspected and the README was read."
            }
          ]
        },
        confidence: 0.9,
        reasoning: "Detected a multi-step validation request that requires observation-driven tool selection."
      };
    }

    if (matchesAny(normalized, ["create", "write", "make", "new"])) {
      return {
        intent: {
          type: "write",
          summary: "Create a file in the scratch workspace.",
          target: {
            kind: "file",
            path: "scratch/agent-output.txt"
          },
          inputs: {
            content: `Generated by lotClaw for goal: ${goal}\n`,
            createDirectories: true
          },
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_create_dirs", value: true }
          ],
          expectedOutcome: 'A file should exist at "scratch/agent-output.txt".',
          proposedSteps: [
            {
              type: "write",
              description: "Write the generated content into the target file.",
              target: {
                kind: "file",
                path: "scratch/agent-output.txt"
              },
              params: {
                content: `Generated by lotClaw for goal: ${goal}\n`,
                createDirectories: true
              }
            },
            {
              type: "finish",
              description: "Report that the file was created."
            }
          ]
        },
        confidence: 0.84,
        reasoning: "Detected a file-creation request."
      };
    }

    if (matchesAny(normalized, ["patch", "replace", "update"])) {
      return {
        intent: {
          type: "patch",
          summary: "Patch a known sentence in README.md.",
          target: {
            kind: "file",
            path: "README.md"
          },
          inputs: {
            find: "lotClaw 是一个面向工具调用、任务规划与执行编排的 Agent Runtime 骨架项目。",
            replace: "lotClaw 是一个面向工具调用、任务规划、文件修改与执行编排的 Agent Runtime 骨架项目。"
          },
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_exist", value: true },
            { kind: "single_replace", value: true }
          ],
          expectedOutcome: 'The README description should be updated in "README.md".',
          proposedSteps: [
            {
              type: "patch",
              description: "Replace the README description with the newer wording.",
              target: {
                kind: "file",
                path: "README.md"
              },
              params: {
                find: "lotClaw 是一个面向工具调用、任务规划与执行编排的 Agent Runtime 骨架项目。",
                replace: "lotClaw 是一个面向工具调用、任务规划、文件修改与执行编排的 Agent Runtime 骨架项目。"
              }
            },
            {
              type: "finish",
              description: "Report that the README was updated."
            }
          ]
        },
        confidence: 0.79,
        reasoning: "Detected a file-update request."
      };
    }

    if (matchesAny(normalized, ["read", "show", "open", "readme"])) {
      return {
        intent: {
          type: "read",
          summary: "Read the repository README file.",
          target: {
            kind: "file",
            path: "README.md"
          },
          inputs: {},
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_exist", value: true }
          ],
          expectedOutcome: 'The contents of "README.md" should be available for summarization.',
          proposedSteps: [
            {
              type: "read",
              description: "Read the README content.",
              target: {
                kind: "file",
                path: "README.md"
              }
            },
            {
              type: "finish",
              description: "Report that the README was read."
            }
          ]
        },
        confidence: 0.81,
        reasoning: "Detected a file-read request."
      };
    }

    return {
      intent: {
        type: "inspect",
        summary: "Inspect the workspace layout.",
        target: {
          kind: "workspace",
          path: "."
        },
        inputs: {},
        constraints: [{ kind: "workspace_only", value: true }],
        expectedOutcome: "A top-level directory listing should be available.",
        proposedSteps: [
          {
            type: "inspect",
            description: "List the workspace root directory.",
            target: {
              kind: "workspace",
              path: "."
            }
          },
          {
            type: "finish",
            description: "Report that the inspection is complete."
          }
        ]
      },
      confidence: 0.62,
      reasoning: "Fell back to workspace inspection."
    };
  }

  async decideNextAction(input: ActionDecisionInput): Promise<NextAction> {
    const { intent, observations } = input;
    const latest = observations.at(-1);

    if (latest && !latest.ok) {
      return {
        type: "finish",
        thought: "The latest tool call failed, so the loop should stop and report the failure.",
        finalOutput: latest.summary
      };
    }

    if (observations.length === 0) {
      if (intent.type === "analyze") {
        return {
          type: "tool_call",
          thought: "To validate the loop, first inspect the workspace before deciding what to read.",
          toolName: "list_dir",
          input: {
            path: intent.target?.path ?? "."
          }
        };
      }

      if (intent.type === "write") {
        return {
          type: "tool_call",
          thought: "The task requires creating a file before anything else.",
          toolName: "write_file",
          input: {
            path: intent.target?.path ?? "scratch/agent-output.txt",
            content: String(intent.inputs.content ?? `Generated by lotClaw for goal: ${input.goal}\n`),
            createDirectories: Boolean(intent.inputs.createDirectories ?? true)
          }
        };
      }

      if (intent.type === "patch") {
        return {
          type: "tool_call",
          thought: "The task requires patching the target file.",
          toolName: "patch_file",
          input: {
            path: intent.target?.path ?? "README.md",
            find: String(intent.inputs.find ?? ""),
            replace: String(intent.inputs.replace ?? "")
          }
        };
      }

      if (intent.type === "read") {
        return {
          type: "tool_call",
          thought: "The task requires reading the target file first.",
          toolName: "read_file",
          input: {
            path: intent.target?.path ?? "README.md"
          }
        };
      }

      return {
        type: "tool_call",
        thought: "The task is exploratory, so start by listing the workspace.",
        toolName: "list_dir",
        input: {
          path: intent.target?.path ?? "."
        }
      };
    }

    if (intent.type === "analyze" && latest?.toolName === "list_dir" && latest.ok) {
      const followUpPath = String(intent.inputs.followUpPath ?? "README.md");
      const entries = extractDirectoryEntries(latest.data);
      const hasFollowUpFile = entries.some((entry) => entry.name === followUpPath && entry.type === "file");

      if (hasFollowUpFile) {
        return {
          type: "tool_call",
          thought: "The inspection confirmed the README exists, so the next step is to read it.",
          toolName: "read_file",
          input: {
            path: followUpPath
          }
        };
      }

      return {
        type: "finish",
        thought: "The workspace inspection completed, but the expected README file was not found.",
        finalOutput: `Workspace inspected, but "${followUpPath}" was not found.`
      };
    }

    return {
      type: "finish",
      thought: "The required tool step has completed, so the task can now be finalized.",
      finalOutput:
        intent.type === "inspect"
          ? "Workspace inspection completed."
          : intent.type === "analyze"
            ? "Workspace inspected and README.md read successfully."
            : intent.summary
    };
  }
}

export class OpenAIModelAdapter implements ModelAdapter {
  readonly name = "openai";

  private readonly client: OpenAI;
  private readonly model: string;

  constructor(options: Required<Pick<ModelAdapterOptions, "apiKey" | "model">> & Pick<ModelAdapterOptions, "baseURL">) {
    this.client = new OpenAI({
      apiKey: options.apiKey,
      baseURL: options.baseURL
    });
    this.model = options.model;
  }

  async generateText(params: ModelGenerateParams): Promise<ModelGenerateResult> {
    const input = buildResponseInput(params);
    const response = await this.client.responses.create({
      model: this.model,
      input
    } as never);

    return {
      outputText: readOutputText(response),
      finishReason: "stop"
    };
  }

  async decideTaskIntent(goal: string): Promise<PlanningDecision> {
    return this.createStructuredResponse<PlanningDecision>({
      prompt: [
        "Classify the user's task into the provided TaskIntent schema.",
        'Return JSON only. Use one of these types: "inspect", "read", "write", "patch", "analyze".',
        "Prefer conservative paths within the current workspace. If uncertain, use inspect."
      ].join(" "),
      userInput: goal,
      schemaName: "task_intent_decision",
      schema: planningDecisionSchema
    });
  }

  async decideNextAction(input: ActionDecisionInput): Promise<NextAction> {
    return this.createStructuredResponse<NextAction>({
      prompt: [
        "Decide the single next action for an agent loop.",
        "You must return either a tool_call action or a finish action.",
        "Only choose tools from the provided availableTools.",
        "If the goal is complete or the latest observation indicates failure, return finish."
      ].join(" "),
      userInput: JSON.stringify(input),
      schemaName: "next_action_decision",
      schema: nextActionSchema
    });
  }

  private async createStructuredResponse<T>(params: {
    prompt: string;
    userInput: string;
    schemaName: string;
    schema: Record<string, unknown>;
  }): Promise<T> {
    const response = await this.client.responses.create({
      model: this.model,
      input: [
        {
          role: "system",
          content: [{ type: "input_text", text: params.prompt }]
        },
        {
          role: "user",
          content: [{ type: "input_text", text: params.userInput }]
        }
      ],
      text: {
        format: {
          type: "json_schema",
          name: params.schemaName,
          schema: params.schema,
          strict: true
        }
      }
    } as never);

    const outputText = readOutputText(response);

    return JSON.parse(outputText) as T;
  }
}

export class OpenAICompatibleChatModelAdapter implements ModelAdapter {
  readonly name: string;

  private readonly client: OpenAI;
  private readonly model: string;

  constructor(
    providerName: string,
    options: Required<Pick<ModelAdapterOptions, "apiKey" | "model">> & Pick<ModelAdapterOptions, "baseURL">
  ) {
    this.name = providerName;
    this.client = new OpenAI({
      apiKey: options.apiKey,
      baseURL: options.baseURL
    });
    this.model = options.model;
  }

  async generateText(params: ModelGenerateParams): Promise<ModelGenerateResult> {
    const response = await this.client.chat.completions.create({
      model: this.model,
      messages: buildChatMessages(params)
    });

    return {
      outputText: readChatCompletionText(response),
      finishReason: "stop"
    };
  }

  async decideTaskIntent(goal: string): Promise<PlanningDecision> {
    return this.generateJson<PlanningDecision>({
      systemPrompt: [
        "Classify the user's task into the provided TaskIntent schema.",
        'Return JSON only. Use one of these types: "inspect", "read", "write", "patch", "analyze".',
        "Prefer conservative paths within the current workspace. If uncertain, use inspect."
      ].join(" "),
      userPrompt: goal
    });
  }

  async decideNextAction(input: ActionDecisionInput): Promise<NextAction> {
    return this.generateJson<NextAction>({
      systemPrompt: [
        "Decide the single next action for an agent loop.",
        "Return JSON only.",
        'Use either {"type":"tool_call",...} or {"type":"finish",...}.',
        "Only choose tools from availableTools.",
        "If the latest observation indicates failure, finish."
      ].join(" "),
      userPrompt: JSON.stringify(input)
    });
  }

  private async generateJson<T>(params: { systemPrompt: string; userPrompt: string }): Promise<T> {
    const response = await this.client.chat.completions.create({
      model: this.model,
      messages: [
        { role: "system", content: `${jsonInstructionPrefix}\n${params.systemPrompt}` },
        { role: "user", content: params.userPrompt }
      ]
    });

    return JSON.parse(extractJsonBlock(readChatCompletionText(response))) as T;
  }
}

export class MiniMaxModelAdapter extends OpenAICompatibleChatModelAdapter {
  constructor(options: Required<Pick<ModelAdapterOptions, "apiKey" | "model">> & Pick<ModelAdapterOptions, "baseURL">) {
    super("minimax", options);
  }
}

export class QwenModelAdapter extends OpenAICompatibleChatModelAdapter {
  constructor(options: Required<Pick<ModelAdapterOptions, "apiKey" | "model">> & Pick<ModelAdapterOptions, "baseURL">) {
    super("qwen", options);
  }
}

export function createModelAdapter(options: ModelAdapterOptions = {}): ModelAdapter {
  const provider = options.provider ?? "stub";

  if (provider === "stub") {
    return new StubModelAdapter();
  }

  if (provider === "openai") {
    if (!options.apiKey) {
      throw new Error('OPENAI_API_KEY is required when MODEL_PROVIDER is "openai".');
    }

    return new OpenAIModelAdapter({
      apiKey: options.apiKey,
      model: options.model ?? "gpt-5.4",
      baseURL: options.baseURL
    });
  }

  if (provider === "minimax") {
    if (!options.apiKey) {
      throw new Error('MINIMAX_API_KEY is required when MODEL_PROVIDER is "minimax".');
    }

    return new MiniMaxModelAdapter({
      apiKey: options.apiKey,
      model: options.model ?? "MiniMax-M2.5",
      baseURL: options.baseURL ?? "https://api.minimax.io/v1"
    });
  }

  if (provider === "qwen") {
    if (!options.apiKey) {
      throw new Error('QWEN_API_KEY is required when MODEL_PROVIDER is "qwen".');
    }

    return new QwenModelAdapter({
      apiKey: options.apiKey,
      model: options.model ?? "qwen-plus",
      baseURL: options.baseURL ?? "https://cn-hongkong.dashscope.aliyuncs.com/compatible-mode/v1"
    });
  }

  throw new Error(`Unsupported model provider "${provider}".`);
}

function buildResponseInput(params: ModelGenerateParams) {
  const input = [];

  if (params.systemPrompt) {
    input.push({
      role: "system",
      content: [{ type: "input_text", text: params.systemPrompt }]
    });
  }

  for (const message of params.messages) {
    input.push({
      role: mapMessageRole(message.role),
      content: [{ type: "input_text", text: message.content }]
    });
  }

  return input;
}

function buildChatMessages(params: ModelGenerateParams): Array<{
  role: "system" | "user" | "assistant";
  content: string;
}> {
  const messages: Array<{ role: "system" | "user" | "assistant"; content: string }> = [];

  if (params.systemPrompt) {
    messages.push({
      role: "system",
      content: params.systemPrompt
    });
  }

  for (const message of params.messages) {
    messages.push({
      role: mapMessageRole(message.role),
      content: message.content
    });
  }

  return messages;
}

function mapMessageRole(role: AgentMessage["role"]): "system" | "user" | "assistant" {
  if (role === "tool") {
    return "assistant";
  }

  return role;
}

function readOutputText(response: unknown): string {
  if (response && typeof response === "object" && "output_text" in response) {
    const outputText = (response as { output_text?: unknown }).output_text;
    if (typeof outputText === "string") {
      return outputText;
    }
  }

  throw new Error("OpenAI response did not contain output_text.");
}

function readChatCompletionText(response: unknown): string {
  if (!response || typeof response !== "object" || !("choices" in response)) {
    throw new Error("Provider response did not contain choices.");
  }

  const choices = (response as { choices?: Array<{ message?: { content?: unknown } }> }).choices;
  const content = choices?.[0]?.message?.content;

  if (typeof content === "string") {
    return content;
  }

  if (Array.isArray(content)) {
    return content
      .map((part) =>
        part && typeof part === "object" && "text" in part
          ? String((part as { text?: unknown }).text ?? "")
          : ""
      )
      .join("");
  }

  throw new Error("Provider response did not contain message content.");
}

function extractJsonBlock(value: string): string {
  const trimmed = value.trim();
  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    return trimmed;
  }

  const fenced =
    trimmed.match(/```json\s*([\s\S]*?)```/i) ??
    trimmed.match(/```\s*([\s\S]*?)```/i);

  if (fenced?.[1]) {
    return fenced[1].trim();
  }

  throw new Error("Model output did not contain valid JSON.");
}

function matchesAny(value: string, patterns: string[]): boolean {
  return patterns.some((pattern) => value.includes(pattern));
}

function extractDirectoryEntries(data: unknown): Array<{ name: string; type: string }> {
  if (!data || typeof data !== "object" || !("entries" in data)) {
    return [];
  }

  const maybeEntries = (data as { entries?: unknown }).entries;
  if (!Array.isArray(maybeEntries)) {
    return [];
  }

  return maybeEntries.filter(isDirectoryEntry);
}

function isDirectoryEntry(value: unknown): value is { name: string; type: string } {
  if (!value || typeof value !== "object") {
    return false;
  }

  return "name" in value && "type" in value;
}

const jsonInstructionPrefix = [
  "Return valid JSON only.",
  "Do not wrap the JSON in markdown fences.",
  "Do not add any explanation before or after the JSON."
].join(" ");

const taskEntityRefSchema = {
  type: "object",
  properties: {
    kind: {
      type: "string",
      enum: ["file", "directory", "workspace", "text"]
    },
    path: { type: "string" },
    value: { type: "string" }
  },
  required: ["kind"],
  additionalProperties: false
} as const;

const taskConstraintSchema = {
  type: "object",
  properties: {
    kind: {
      type: "string",
      enum: ["workspace_only", "must_create_dirs", "must_exist", "single_replace"]
    },
    value: {
      anyOf: [{ type: "boolean" }, { type: "string" }]
    }
  },
  required: ["kind", "value"],
  additionalProperties: false
} as const;

const taskIntentStepSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      enum: ["inspect", "read", "write", "patch", "analyze", "finish"]
    },
    description: { type: "string" },
    target: taskEntityRefSchema,
    params: {
      type: "object",
      additionalProperties: {
        anyOf: [{ type: "string" }, { type: "boolean" }, { type: "number" }]
      }
    }
  },
  required: ["type", "description"],
  additionalProperties: false
} as const;

const planningDecisionSchema = {
  type: "object",
  properties: {
    intent: {
      type: "object",
      properties: {
        type: {
          type: "string",
          enum: ["inspect", "read", "write", "patch", "analyze"]
        },
        summary: { type: "string" },
        target: taskEntityRefSchema,
        inputs: {
          type: "object",
          additionalProperties: {
            anyOf: [{ type: "string" }, { type: "boolean" }, { type: "number" }]
          }
        },
        constraints: {
          type: "array",
          items: taskConstraintSchema
        },
        expectedOutcome: { type: "string" },
        proposedSteps: {
          type: "array",
          items: taskIntentStepSchema
        }
      },
      required: ["type", "summary", "inputs", "constraints", "expectedOutcome", "proposedSteps"],
      additionalProperties: false
    },
    confidence: { type: "number" },
    reasoning: { type: "string" }
  },
  required: ["intent", "confidence", "reasoning"],
  additionalProperties: false
} as const;

const nextActionSchema = {
  oneOf: [
    {
      type: "object",
      properties: {
        type: {
          type: "string",
          const: "tool_call"
        },
        toolName: { type: "string" },
        input: {
          type: "object",
          additionalProperties: true
        },
        thought: { type: "string" }
      },
      required: ["type", "toolName", "input", "thought"],
      additionalProperties: false
    },
    {
      type: "object",
      properties: {
        type: {
          type: "string",
          const: "finish"
        },
        finalOutput: { type: "string" },
        thought: { type: "string" }
      },
      required: ["type", "finalOutput", "thought"],
      additionalProperties: false
    }
  ]
} as const;
