import type { AgentMessage } from "@lotclaw/shared-types";

export interface ModelGenerateParams {
  systemPrompt?: string;
  messages: AgentMessage[];
}

export interface ModelGenerateResult {
  outputText: string;
  finishReason: "stop" | "length" | "tool_call";
}

export type TaskIntentType = "inspect" | "read" | "write" | "patch" | "analyze";

export interface TaskEntityRef {
  kind: "file" | "directory" | "workspace" | "text";
  path?: string;
  value?: string;
}

export interface TaskConstraint {
  kind: "workspace_only" | "must_create_dirs" | "must_exist" | "single_replace";
  value: boolean | string;
}

export interface TaskIntentStep {
  type: "inspect" | "read" | "write" | "patch" | "analyze" | "finish";
  description: string;
  target?: TaskEntityRef;
  params?: Record<string, string | boolean | number>;
}

export interface TaskIntentSchema {
  type: TaskIntentType;
  summary: string;
  target?: TaskEntityRef;
  inputs: Record<string, string | boolean | number>;
  constraints: TaskConstraint[];
  expectedOutcome: string;
  proposedSteps: TaskIntentStep[];
}

export interface PlanningDecision {
  intent: TaskIntentSchema;
  confidence: number;
  reasoning: string;
}

export interface ToolDescriptor {
  name: string;
  description: string;
  permission: string;
}

export interface ActionObservation {
  toolName: string;
  ok: boolean;
  summary: string;
  data?: unknown;
  errorCode?: string;
}

export type NextAction =
  | {
      type: "tool_call";
      toolName: string;
      input: Record<string, unknown>;
      thought: string;
    }
  | {
      type: "finish";
      finalOutput: string;
      thought: string;
    };

export interface ActionDecisionInput {
  goal: string;
  intent: TaskIntentSchema;
  availableTools: ToolDescriptor[];
  observations: ActionObservation[];
}

export interface ModelAdapter {
  name: string;
  generateText(params: ModelGenerateParams): Promise<ModelGenerateResult>;
  decideTaskIntent(goal: string): Promise<PlanningDecision>;
  decideNextAction(input: ActionDecisionInput): Promise<NextAction>;
}

export class StubModelAdapter implements ModelAdapter {
  name = "stub";

  async generateText(params: ModelGenerateParams): Promise<ModelGenerateResult> {
    const latest = params.messages[params.messages.length - 1];

    return {
      outputText: latest ? `stub:${latest.content}` : "stub:empty",
      finishReason: "stop"
    };
  }

  async decideTaskIntent(goal: string): Promise<PlanningDecision> {
    const normalized = goal.trim().toLowerCase();

    if (matchesAny(normalized, ["validate loop", "analyze readme", "inspect then read", "agent loop"])) {
      return {
        intent: {
          type: "analyze",
          summary: "Inspect the workspace and then read README.md if it exists.",
          target: {
            kind: "workspace",
            path: "."
          },
          inputs: {
            followUpPath: "README.md"
          },
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_exist", value: true }
          ],
          expectedOutcome: 'The agent should first inspect the workspace, then read "README.md", then finish.',
          proposedSteps: [
            {
              type: "inspect",
              description: "List the workspace root to confirm the README is present.",
              target: {
                kind: "workspace",
                path: "."
              }
            },
            {
              type: "read",
              description: "Read README.md after confirming it exists.",
              target: {
                kind: "file",
                path: "README.md"
              }
            },
            {
              type: "finish",
              description: "Report that the workspace was inspected and the README was read."
            }
          ]
        },
        confidence: 0.9,
        reasoning: "Detected a multi-step validation request that requires observation-driven tool selection."
      };
    }

    if (matchesAny(normalized, ["create", "write", "make", "new"])) {
      return {
        intent: {
          type: "write",
          summary: "Create a file in the scratch workspace.",
          target: {
            kind: "file",
            path: "scratch/agent-output.txt"
          },
          inputs: {
            content: `Generated by lotClaw for goal: ${goal}\n`,
            createDirectories: true
          },
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_create_dirs", value: true }
          ],
          expectedOutcome: 'A file should exist at "scratch/agent-output.txt".',
          proposedSteps: [
            {
              type: "write",
              description: "Write the generated content into the target file.",
              target: {
                kind: "file",
                path: "scratch/agent-output.txt"
              },
              params: {
                content: `Generated by lotClaw for goal: ${goal}\n`,
                createDirectories: true
              }
            },
            {
              type: "finish",
              description: "Report that the file was created."
            }
          ]
        },
        confidence: 0.84,
        reasoning: "Detected a file-creation request."
      };
    }

    if (matchesAny(normalized, ["patch", "replace", "update"])) {
      return {
        intent: {
          type: "patch",
          summary: "Patch a known sentence in README.md.",
          target: {
            kind: "file",
            path: "README.md"
          },
          inputs: {
            find: "lotClaw 是一个面向工具调用、任务规划与执行编排的 Agent Runtime 骨架项目。",
            replace: "lotClaw 是一个面向工具调用、任务规划、文件修改与执行编排的 Agent Runtime 骨架项目。"
          },
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_exist", value: true },
            { kind: "single_replace", value: true }
          ],
          expectedOutcome: 'The README description should be updated in "README.md".',
          proposedSteps: [
            {
              type: "patch",
              description: "Replace the README description with the newer wording.",
              target: {
                kind: "file",
                path: "README.md"
              },
              params: {
                find: "lotClaw 是一个面向工具调用、任务规划与执行编排的 Agent Runtime 骨架项目。",
                replace: "lotClaw 是一个面向工具调用、任务规划、文件修改与执行编排的 Agent Runtime 骨架项目。"
              }
            },
            {
              type: "finish",
              description: "Report that the README was updated."
            }
          ]
        },
        confidence: 0.79,
        reasoning: "Detected a file-update request."
      };
    }

    if (matchesAny(normalized, ["read", "show", "open", "readme"])) {
      return {
        intent: {
          type: "read",
          summary: "Read the repository README file.",
          target: {
            kind: "file",
            path: "README.md"
          },
          inputs: {},
          constraints: [
            { kind: "workspace_only", value: true },
            { kind: "must_exist", value: true }
          ],
          expectedOutcome: 'The contents of "README.md" should be available for summarization.',
          proposedSteps: [
            {
              type: "read",
              description: "Read the README content.",
              target: {
                kind: "file",
                path: "README.md"
              }
            },
            {
              type: "finish",
              description: "Report that the README was read."
            }
          ]
        },
        confidence: 0.81,
        reasoning: "Detected a file-read request."
      };
    }

    return {
      intent: {
        type: "inspect",
        summary: "Inspect the workspace layout.",
        target: {
          kind: "workspace",
          path: "."
        },
        inputs: {},
        constraints: [{ kind: "workspace_only", value: true }],
        expectedOutcome: "A top-level directory listing should be available.",
        proposedSteps: [
          {
            type: "inspect",
            description: "List the workspace root directory.",
            target: {
              kind: "workspace",
              path: "."
            }
          },
          {
            type: "finish",
            description: "Report that the inspection is complete."
          }
        ]
      },
      confidence: 0.62,
      reasoning: "Fell back to workspace inspection."
    };
  }

  async decideNextAction(input: ActionDecisionInput): Promise<NextAction> {
    const { intent, observations } = input;
    const latest = observations.at(-1);

    if (latest && !latest.ok) {
      return {
        type: "finish",
        thought: "The latest tool call failed, so the loop should stop and report the failure.",
        finalOutput: latest.summary
      };
    }

    if (observations.length === 0) {
      if (intent.type === "analyze") {
        return {
          type: "tool_call",
          thought: "To validate the loop, first inspect the workspace before deciding what to read.",
          toolName: "list_dir",
          input: {
            path: intent.target?.path ?? "."
          }
        };
      }

      if (intent.type === "write") {
        return {
          type: "tool_call",
          thought: "The task requires creating a file before anything else.",
          toolName: "write_file",
          input: {
            path: intent.target?.path ?? "scratch/agent-output.txt",
            content:
              String(intent.inputs.content ?? `Generated by lotClaw for goal: ${input.goal}\n`),
            createDirectories: Boolean(intent.inputs.createDirectories ?? true)
          }
        };
      }

      if (intent.type === "patch") {
        return {
          type: "tool_call",
          thought: "The task requires patching the target file.",
          toolName: "patch_file",
          input: {
            path: intent.target?.path ?? "README.md",
            find: String(intent.inputs.find ?? ""),
            replace: String(intent.inputs.replace ?? "")
          }
        };
      }

      if (intent.type === "read") {
        return {
          type: "tool_call",
          thought: "The task requires reading the target file first.",
          toolName: "read_file",
          input: {
            path: intent.target?.path ?? "README.md"
          }
        };
      }

      return {
        type: "tool_call",
        thought: "The task is exploratory, so start by listing the workspace.",
        toolName: "list_dir",
        input: {
          path: intent.target?.path ?? "."
        }
      };
    }

    if (intent.type === "analyze" && latest?.toolName === "list_dir" && latest.ok) {
      const followUpPath = String(intent.inputs.followUpPath ?? "README.md");
      const entries = extractDirectoryEntries(latest.data);
      const hasFollowUpFile = entries.some((entry) => entry.name === followUpPath && entry.type === "file");

      if (hasFollowUpFile) {
        return {
          type: "tool_call",
          thought: "The inspection confirmed the README exists, so the next step is to read it.",
          toolName: "read_file",
          input: {
            path: followUpPath
          }
        };
      }

      return {
        type: "finish",
        thought: "The workspace inspection completed, but the expected README file was not found.",
        finalOutput: `Workspace inspected, but "${followUpPath}" was not found.`
      };
    }

    return {
      type: "finish",
      thought: "The required tool step has completed, so the task can now be finalized.",
      finalOutput:
        intent.type === "inspect"
          ? "Workspace inspection completed."
          : intent.type === "analyze"
            ? "Workspace inspected and README.md read successfully."
            : intent.summary
    };
  }
}

function matchesAny(value: string, patterns: string[]): boolean {
  return patterns.some((pattern) => value.includes(pattern));
}

function extractDirectoryEntries(data: unknown): Array<{ name: string; type: string }> {
  if (!data || typeof data !== "object" || !("entries" in data)) {
    return [];
  }

  const maybeEntries = (data as { entries?: unknown }).entries;
  if (!Array.isArray(maybeEntries)) {
    return [];
  }

  return maybeEntries.filter(isDirectoryEntry);
}

function isDirectoryEntry(value: unknown): value is { name: string; type: string } {
  if (!value || typeof value !== "object") {
    return false;
  }

  return "name" in value && "type" in value;
}
